spring.application.name=elixir-service
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/elixir_db?useSSL=false&serverTimezone=Asia/Dhaka&allowPublicKeyRetrieval=true
spring.datasource.username=elixir_db
spring.datasource.password=elixir_db@007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

jwt.secret=${JWT_SECRET:change-this-development-secret-change-before-production-change}
jwt.access-token-expiration=900000
app.upload.base-dir=uploads
app.upload.public-path=/uploads